# Generated by Django 5.1.7 on 2025-03-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_transaction_type_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
